<?php
/**
 * Compatibility Patch Generator — writes mu-plugin files for auto-fixes.
 *
 * All auto-fix patches are stored as individual PHP files inside
 * wp-content/mu-plugins/jetstrike-patches/. A loader mu-plugin file
 * includes all patches from that directory.
 *
 * This approach ensures patches load before any regular plugins (mu-plugins
 * load first), and each patch can be individually removed/reverted.
 *
 * @package Jetstrike\ConflictDetector
 */

declare(strict_types=1);

namespace Jetstrike\ConflictDetector\Resolver;

final class CompatibilityPatch {

    /** @var string Directory name inside mu-plugins. */
    private const PATCH_DIR = 'jetstrike-patches';

    /** @var string Loader filename in mu-plugins root. */
    private const LOADER_FILE = 'jetstrike-patch-loader.php';

    /**
     * Write a patch file and ensure the loader exists.
     *
     * @param int    $conflict_id  Conflict ID for unique filename.
     * @param string $fix_type     Type of fix (hook_priority, script_dequeue, etc.).
     * @param string $code         PHP code to write (without opening <?php tag).
     * @param string $description  Human-readable description of the patch.
     * @return string|null Filename on success, null on failure.
     */
    public function write_patch(int $conflict_id, string $fix_type, string $code, string $description): ?string {
        if ($conflict_id <= 0) {
            return null;
        }

        $patch_dir = $this->ensure_patch_dir();

        if ($patch_dir === null) {
            return null;
        }

        $this->ensure_loader();

        $filename = sprintf(
            'jetstrike-fix-%d-%s.php',
            $conflict_id,
            sanitize_file_name($fix_type)
        );

        $full_path = $patch_dir . '/' . $filename;

        $file_content = "<?php\n";
        $file_content .= "/**\n";
        $file_content .= " * Jetstrike Auto-Fix Patch\n";
        $file_content .= " *\n";
        $file_content .= " * " . str_replace("\n", "\n * ", $description) . "\n";
        $file_content .= " *\n";
        $file_content .= " * Conflict ID: {$conflict_id}\n";
        $file_content .= " * Fix Type: {$fix_type}\n";
        $file_content .= " * Generated: " . current_time('mysql', true) . "\n";
        $file_content .= " *\n";
        $file_content .= " * This file was auto-generated by Jetstrike Conflict Detector.\n";
        $file_content .= " * To revert this fix, delete this file or use the Jetstrike dashboard.\n";
        $file_content .= " *\n";
        $file_content .= " * @package Jetstrike\\ConflictDetector\\Patches\n";
        $file_content .= " */\n\n";
        $file_content .= "if (! defined('ABSPATH')) { exit; }\n\n";
        $file_content .= $code . "\n";

        // Use WP_Filesystem for safe file writing.
        global $wp_filesystem;

        if (empty($wp_filesystem)) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
            WP_Filesystem();
        }

        if ($wp_filesystem && $wp_filesystem->put_contents($full_path, $file_content, FS_CHMOD_FILE)) {
            return $filename;
        }

        // Fallback to direct file write if WP_Filesystem fails.
        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        $written = file_put_contents($full_path, $file_content);

        return $written !== false ? $filename : null;
    }

    /**
     * Remove a patch file.
     *
     * @param string $filename Patch filename.
     * @return bool True if file was removed.
     */
    public function remove_patch(string $filename): bool {
        $patch_dir = WPMU_PLUGIN_DIR . '/' . self::PATCH_DIR;
        $full_path = $patch_dir . '/' . sanitize_file_name($filename);

        if (file_exists($full_path)) {
            wp_delete_file($full_path);
            return ! file_exists($full_path);
        }

        return true;
    }

    /**
     * Remove all Jetstrike patches.
     *
     * @return int Number of patches removed.
     */
    public function remove_all_patches(): int {
        $patch_dir = WPMU_PLUGIN_DIR . '/' . self::PATCH_DIR;
        $count = 0;

        if (! is_dir($patch_dir)) {
            return 0;
        }

        $files = glob($patch_dir . '/jetstrike-fix-*.php');

        if ($files === false) {
            return 0;
        }

        foreach ($files as $file) {
            wp_delete_file($file);

            if (! file_exists($file)) {
                $count++;
            }
        }

        // Remove the loader if no patches remain.
        $remaining = glob($patch_dir . '/jetstrike-fix-*.php');

        if (empty($remaining)) {
            $loader = WPMU_PLUGIN_DIR . '/' . self::LOADER_FILE;

            if (file_exists($loader)) {
                wp_delete_file($loader);
            }

            // Remove the patch directory.
            @rmdir($patch_dir);
        }

        return $count;
    }

    /**
     * List all active patch files.
     *
     * @return array<string, array{file: string, conflict_id: int, fix_type: string}>
     */
    public function list_patches(): array {
        $patch_dir = WPMU_PLUGIN_DIR . '/' . self::PATCH_DIR;

        if (! is_dir($patch_dir)) {
            return [];
        }

        $files = glob($patch_dir . '/jetstrike-fix-*.php');

        if ($files === false) {
            return [];
        }

        $patches = [];

        foreach ($files as $file) {
            $filename = basename($file);
            $matches = [];

            if (preg_match('/^jetstrike-fix-(\d+)-(.+)\.php$/', $filename, $matches)) {
                $patches[$filename] = [
                    'file'        => $filename,
                    'conflict_id' => (int) $matches[1],
                    'fix_type'    => $matches[2],
                    'size'        => filesize($file),
                    'modified'    => filemtime($file),
                ];
            }
        }

        return $patches;
    }

    /**
     * Ensure the patch directory exists and is writable.
     *
     * @return string|null Directory path on success, null on failure.
     */
    private function ensure_patch_dir(): ?string {
        $dir = WPMU_PLUGIN_DIR . '/' . self::PATCH_DIR;

        if (! is_dir(WPMU_PLUGIN_DIR)) {
            wp_mkdir_p(WPMU_PLUGIN_DIR);
        }

        if (! is_dir($dir)) {
            wp_mkdir_p($dir);
        }

        if (! is_dir($dir) || ! is_writable($dir)) {
            return null;
        }

        // Add an index.php for security.
        $index = $dir . '/index.php';

        if (! file_exists($index)) {
            // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
            file_put_contents($index, "<?php\n// Silence is golden.\n");
        }

        return $dir;
    }

    /**
     * Ensure the mu-plugin loader file exists.
     *
     * The loader includes all patch files from the jetstrike-patches directory.
     * This is necessary because WordPress only auto-loads mu-plugins from the
     * root mu-plugins directory, not subdirectories.
     */
    private function ensure_loader(): void {
        $loader_path = WPMU_PLUGIN_DIR . '/' . self::LOADER_FILE;

        if (file_exists($loader_path)) {
            return;
        }

        $loader_code = <<<'PHP'
<?php
/**
 * Jetstrike Conflict Detector — Patch Loader
 *
 * Automatically loads all compatibility patches generated by Jetstrike.
 * Do not edit this file directly. Manage patches from the Jetstrike dashboard.
 *
 * @package Jetstrike\ConflictDetector\Patches
 */

if (! defined('ABSPATH')) {
    exit;
}

$jetstrike_patch_dir = __DIR__ . '/jetstrike-patches';

if (is_dir($jetstrike_patch_dir)) {
    $patches = glob($jetstrike_patch_dir . '/jetstrike-fix-*.php');

    if (is_array($patches)) {
        foreach ($patches as $patch) {
            require_once $patch;
        }
    }
}
PHP;

        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        file_put_contents($loader_path, $loader_code);
    }
}
